### ISSUE TITLE
Clarification on height

### ISSUE THREAD

**Issue by beeshyams** [boudhayan-dev/Blind-Reader#5]
Thanks fir your work and sorry for raising this as in issue.

I wanted to fabricate a stand similar to yours and was wondering what the height of stand is. I have ver 1.3 camera board, if it matters

**Comment by boudhayan-dev** [comment]
If I remember right, the stand was 40 cm in height. It needs to be calibrated based on the resolution of your camera. You could start from 40cm and adjust accordingly based on the clarity of the images.
